export const ICON_PRESETS = [
  { id: 'Code2', label: 'React / Next.js / Code', category: 'Frontend' },
  { id: 'FileCode', label: 'JavaScript / TypeScript', category: 'Frontend' },
  { id: 'Palette', label: 'Tailwind CSS / Styling', category: 'Frontend' },
  { id: 'Layout', label: 'HTML5 / Web Layout', category: 'Frontend' },
  { id: 'Smartphone', label: 'Mobile / React Native', category: 'Frontend' },
  { id: 'Server', label: 'Node.js / Backend', category: 'Backend' },
  { id: 'Network', label: 'REST API / GraphQL', category: 'Backend' },
  { id: 'ShieldCheck', label: 'Auth / Security / JWT', category: 'Backend' },
  { id: 'Database', label: 'PostgreSQL / MySQL', category: 'Database' },
  { id: 'HardDrive', label: 'SQLite / MongoDB', category: 'Database' },
  { id: 'Layers', label: 'Prisma ORM / Models', category: 'Database' },
  { id: 'GitBranch', label: 'Git / GitHub', category: 'DevOps & Tools' },
  { id: 'Cpu', label: 'Docker / CI-CD', category: 'DevOps & Tools' },
  { id: 'Cloud', label: 'Cloud / Vercel / AWS', category: 'DevOps & Tools' },
  { id: 'Figma', label: 'Figma / UI-UX Design', category: 'Design' },
  { id: 'Terminal', label: 'Bash / Linux / CLI', category: 'Tools' },
  { id: 'Workflow', label: 'Automation / Workflow', category: 'Tools' },
  { id: 'Globe', label: 'Web Standards / SEO', category: 'General' },
];
